### ISSUE TITLE
[BUG REPORT] Maven clean package WARNINGS and ERRORS

### ISSUE THREAD

**Issue by enyopessoa** [tr7zw/Mango-Companion#100]
Hi, good afternoon. I've encountered some bugs, errors and write some solutions that I'd like to report when I've tried to compile it.

Maven version that I use:
```
$ mvn -version
Apache Maven 3.6.3
Maven home: /usr/share/maven
Java version: 11.0.17, vendor: Ubuntu, runtime: /usr/lib/jvm/java-11-openjdk-amd64
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.15.0-53-generic", arch: "amd64", family: "unix"

```
==============================================================================

### WARNINGS
```
$ mvn clean package
[INFO] Scanning for projects...
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for dev.tr7zw:mango-companion:jar:0.0.1-SNAPSHOT
[WARNING] 'dependencies.dependency.(groupId:artifactId:type:classifier)' must be unique: io.github.openfeign:feign-core:jar -> duplicate declaration of version 12.1 @ line 121, column 21
[WARNING] 'dependencies.dependency.(groupId:artifactId:type:classifier)' must be unique: io.github.openfeign:feign-gson:jar -> duplicate declaration of version 12.1 @ line 126, column 21
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-compiler-plugin is missing. @ line 153, column 12
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 
```

=======================================

### SOLUTION 1

- Duplicate declaration of version. Solution: remove duplicate lines 121-130 from pom.xml:

```
		<dependency>
			<groupId>io.github.openfeign</groupId>
			<artifactId>feign-core</artifactId>
			<version>12.1</version>
		</dependency>
		<dependency>
			<groupId>io.github.openfeign</groupId>
			<artifactId>feign-gson</artifactId>
			<version>12.1</version>
```

### SOLUTION 2
- Error: maven-compiler-plugin is missing from pom.xml . Solution: 

Before:

```
	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<configuration>
					<source>1.8</source>
					<target>1.8</target>
				</configuration>
			</plugin>
```

After line 155, add:

                		<version>3.8.1</version>

It becomes:

```
	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
                		<version>3.8.1</version>
				<configuration>
					<source>1.8</source>
					<target>1.8</target>
				</configuration>
			</plugin>
```

=================================================================================

### ERROR 1

```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  2.968 s
[INFO] Finished at: 2022-12-28T11:45:47-04:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project mango-companion: Could not resolve dependencies for project dev.tr7zw:mango-companion:jar:0.0.1-SNAPSHOT: Failed to collect dependencies at org.ehcache:ehcache:jar:3.10.8 -> org.glassfish.jaxb:jaxb-runtime:jar:2.3.0-b170127.1453 -> org.glassfish.jaxb:jaxb-core:jar:2.3.0-b170127.1453 -> javax.xml.bind:jaxb-api:jar:2.3.0-b161121.1438: Failed to read artifact descriptor for javax.xml.bind:jaxb-api:jar:2.3.0-b161121.1438: Could not transfer artifact javax.xml.bind:jaxb-api:pom:2.3.0-b161121.1438 from/to netbeans (http://bits.netbeans.org/nexus/content/groups/netbeans): Authentication failed for http://bits.netbeans.org/nexus/content/groups/netbeans/javax/xml/bind/jaxb-api/2.3.0-b161121.1438/jaxb-api-2.3.0-b161121.1438.pom 401 Repository decommissioned. Please refer to https://netbeans.apache.org/about/oracle-transition.html for more information. -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
```

======================================================================

### POSSIBLE SOLUTION

Since it can't resolve the dependency - because the repository is decommissioned - I excluded the jaxb-runtime from pom.xml in the dependency tree.

Before:

```
		<dependency>
			<groupId>org.ehcache</groupId>
			<artifactId>ehcache</artifactId>
			<version>3.10.8</version>
		</dependency>
```

After line 86, add:

```
				<exclusions>
                			<exclusion>
		                	<groupId>org.glassfish.jaxb</groupId>
                    			<artifactId>jaxb-runtime</artifactId>
					</exclusion>
            			</exclusions>
```

It becomes:

```
		<dependency>
			<groupId>org.ehcache</groupId>
			<artifactId>ehcache</artifactId>
			<version>3.10.8</version>
				<exclusions>
                			<exclusion>
		                	<groupId>org.glassfish.jaxb</groupId>
                    			<artifactId>jaxb-runtime</artifactId>
					</exclusion>
            			</exclusions>
		</dependency>
```

====================================================================================

### ERROR 2

When the script is testing those sites:

```
Tests run: 3, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 2.436 sec <<< FAILURE!
testChapters(dev.tr7zw.mango_companion.MangatxTest)  Time elapsed: 1.396 sec  <<< ERROR!
feign.FeignException$NotFound: [404 ] during [GET] to [https://mangatx.com/manga/reformation-of-the-deadbeat-noble/] [MadaraAPI#getMangaInfo(String)]: [<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL was not found on this server.</p>
<p>Additionally, a 404 Not Found
error was encountered while trying to use an ErrorDocument to handle the request.</p>
</body></html>
]
	at feign.FeignException.clientErrorStatus(FeignException.java:228)
	at feign.FeignException.errorStatus(FeignException.java:203)
	at feign.FeignException.errorStatus(FeignException.java:194)
	at feign.FeignException.errorStatus(FeignException.java:171)
	at feign.codec.ErrorDecoder$Default.decode(ErrorDecoder.java:92)
	at feign.ResponseHandler.decodeError(ResponseHandler.java:136)
	at feign.ResponseHandler.handleResponse(ResponseHandler.java:70)
	at feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:116)
	at feign.SynchronousMethodHandler.invoke(SynchronousMethodHandler.java:72)
	at feign.ReflectiveFeign$FeignInvocationHandler.invoke(ReflectiveFeign.java:98)
	at dev.tr7zw.mango_companion.util.parser.$Proxy14.getMangaInfo(Unknown Source)
	at dev.tr7zw.mango_companion.util.parser.AbstractMadaraParser.getChapters(AbstractMadaraParser.java:90)
	at dev.tr7zw.mango_companion.util.parser.StandardLayoutParser.getChapters(StandardLayoutParser.java:51)
	at dev.tr7zw.mango_companion.MangatxTest.testChapters(MangatxTest.java:52)

testName(dev.tr7zw.mango_companion.MangatxTest)  Time elapsed: 1.033 sec  <<< ERROR!
feign.FeignException$NotFound: [404 ] during [GET] to [https://mangatx.com/manga/the-player-that-cant-level-up/] [MadaraAPI#getMangaInfo(String)]: [<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL was not found on this server.</p>
<p>Additionally, a 404 Not Found
error was encountered while trying to use an ErrorDocument to handle the request.</p>
</body></html>
]
	at feign.FeignException.clientErrorStatus(FeignException.java:228)
	at feign.FeignException.errorStatus(FeignException.java:203)
	at feign.FeignException.errorStatus(FeignException.java:194)
	at feign.FeignException.errorStatus(FeignException.java:171)
	at feign.codec.ErrorDecoder$Default.decode(ErrorDecoder.java:92)
	at feign.ResponseHandler.decodeError(ResponseHandler.java:136)
	at feign.ResponseHandler.handleResponse(ResponseHandler.java:70)
	at feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:116)
	at feign.SynchronousMethodHandler.invoke(SynchronousMethodHandler.java:72)
	at feign.ReflectiveFeign$FeignInvocationHandler.invoke(ReflectiveFeign.java:98)
	at dev.tr7zw.mango_companion.util.parser.$Proxy14.getMangaInfo(Unknown Source)
	at dev.tr7zw.mango_companion.util.APIProxyBuilder$1.getMangaInfo(APIProxyBuilder.java:17)
	at dev.tr7zw.mango_companion.util.parser.StandardLayoutParser.getName(StandardLayoutParser.java:37)
	at dev.tr7zw.mango_companion.MangatxTest.testName(MangatxTest.java:47)

Running dev.tr7zw.mango_companion.FlamescansTest
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 10.594 sec
Running dev.tr7zw.mango_companion.ChapterParserTest
Tests run: 7, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.002 sec
Running dev.tr7zw.mango_companion.MangadexTest
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 14.372 sec
Running dev.tr7zw.mango_companion.AsuraScansTest
Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 18.894 sec

Results :

Tests in error: 
  testChapters(dev.tr7zw.mango_companion.MangatxTest): [404 ] during [GET] to [https://mangatx.com/manga/reformation-of-the-deadbeat-noble/] [MadaraAPI#getMangaInfo(String)]: [<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">(..)
  testName(dev.tr7zw.mango_companion.MangatxTest): [404 ] during [GET] to [https://mangatx.com/manga/the-player-that-cant-level-up/] [MadaraAPI#getMangaInfo(String)]: [<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">(..)

Tests run: 32, Failures: 0, Errors: 2, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  09:49 min
[INFO] Finished at: 2022-12-28T12:02:19-04:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test (default-test) on project mango-companion: There are test failures.
[ERROR] 
[ERROR] Please refer to /home/stark/Documents/Mango-companion_master2/Mango-Companion-master/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

```
==============================================================

### SOLUTION

Mangatx is down. Need to bypass this site.

**Comment by tr7zw** [comment]
Hm, seems like some degradation that started to stack up over time/due to dependabot. Will have to check when I've got time to look into these.
